name: dramahub_admin
description: DramaHub Admin Panel
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.6.6

  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0

  url_launcher: ^6.3.2

  # HTTP client
  dio: ^5.4.0

  # Local storage (Web compatible)
  localstorage: ^4.0.0+1

  # Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
